Style/EachWithObject:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/Next:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceInsideRangeLiteral:
  Enabled: false
Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
