Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceInsideRangeLiteral:
  Enabled: false
Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
