Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
