sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby-9.0.0.0
  - rbx-2.2.7
gemfile: Gemfile
env:
  - MATHN=true RUBOCOP=false
  - MATHN=false RUBOCOP=false
branches:
  only:
    - master
    - stable
    - stable_3_2
notifications:
  irc: {channels: "irc.freenode.org#sass"}
matrix:
  allow_failures:
    - rvm: rbx-2.2.7
    - rvm: jruby-9.0.0.0
  include:
    - rvm: 2.2.3
      env: MATHN=true RUBOCOP=true
    - rvm: 2.1.7
      env: MATHN=true RUBOCOP=true
    - rvm: 2.0.0
      env: MATHN=true RUBOCOP=true

